### 前沿图
GET http://localhost:9301/result/list/25


### 空间拓扑图
GET http://localhost:9301/result/pheno/1



### 二维矩形图
GET http://localhost:9301/result/2dr/1?primarytype=Phi&category=测向误差

### 二维矩形图
GET http://localhost:9301/result/2dr/1?primarytype=Phi&category=测向误差&unit=rad

### 二维矩形图
GET http://localhost:9301/result/2dr/1?primarytype=Phi&category=第二相关峰

