name: Java CI on Windows with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Deploy to Windows Server via PowerShell
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"

          $Password = ConvertTo-SecureString "${{ secrets.PASSWORD }}" -AsPlainText -Force
          $Cred = New-Object System.Management.Automation.PSCredential("${{ secrets.USERNAME }}", $Password)

          $Session = New-PSSession -ComputerName ${{ secrets.HOST }} -Credential $Cred

          # 复制构建产物到远程服务器
          Copy-Item -Path .\target\springboot.jar -Destination "C:\deploy\" -ToSession $Session -Force

          # 重启 SpringBoot 应用
          Invoke-Command -Session $Session -ScriptBlock {
            $JarPath = "C:\deploy\springboot.jar"
            $Process = Get-Process | Where-Object { $_.Path -eq $JarPath }
            if ($Process) {
              Stop-Process -Id $Process.Id -Force
              Write-Host "已停止旧进程：$($Process.Id)"
            } else {
              Write-Host "未找到旧进程"
            }

            Start-Process "java" "-jar -Xmx1024M -Xms256M $JarPath"
            Write-Host "新进程已启动"
          }

          Remove-PSSession $Session
