name: Java CI & Deploy (WinRM HTTP, JDK 17)

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # ① 拉代码
      - uses: actions/checkout@v3

      # ② 安装 JDK 17（Temurin）
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven          # 仍然可用 Maven 缓存

      # ③ Maven 打包
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      # ④ 部署到远程 Windows
      - name: Deploy via WinRM (HTTP 5985, Basic)
        shell: pwsh
        run: |
          Set-Item WSMan:\localhost\Client\Auth\Basic   -Value $true
          Set-Item WSMan:\localhost\Client\AllowUnencrypted -Value $true   
          Set-Item WSMan:\localhost\Client\TrustedHosts -Value "${{ secrets.HOST }}" -Force


          $Password = ConvertTo-SecureString "${{ secrets.PASSWORD }}" -AsPlainText -Force
          $Cred     = New-Object System.Management.Automation.PSCredential("${{ secrets.USERNAME }}", $Password)


          $Session = New-PSSession -ComputerName ${{ secrets.HOST }} `
                     -Credential $Cred -Authentication Basic


          Copy-Item -Path .\target\springboot.jar `
            -Destination 'C:\deploy\' -ToSession $Session -Force


          Invoke-Command -Session $Session -ScriptBlock {
            $Jar = 'C:\deploy\springboot.jar'
            $p   = Get-Process | Where-Object { $_.Path -eq $Jar }
            if ($p) {
              Stop-Process -Id $p.Id -Force
              Write-Host "已停止旧进程 $($p.Id)"
            }
            Start-Process "java" "-jar -Xmx1024M -Xms256M $Jar"
            Write-Host "新进程已启动"
          }


          Remove-PSSession $Session
